### ISSUE TITLE
Authorization fails due to introduction of JSON web token

### ISSUE THREAD

**Issue by telekineticyeti** [joaopsys/AutoChronoGG#1]
Hi there,

As subject: the cookie is no longer sufficient to access the endpoint. An additional authorisation header is required that contains a JSON web token (JWT) pulled from session storage. Without this, the program returns the following error:  HTTP Error 401: Unauthorized.

I can get around this issue by hard-coding the authorization header into the script, copied from a chrome session.

**Comment by xJota** [comment]
Hello!

I am aware of this, but thank you for reporting! I will update the README as soon as I can, with a simple way to extract the JWT.

Sorry for my delayed reply!

**Comment by joaopsys** [comment]
I've updated the README. Should be simple enough for anyone to extract the token.
