### ISSUE TITLE
<<<AutoChronoGG>>> <line 144>

### ISSUE THREAD

**Issue by stickerx** [joaopsys/AutoChronoGG#11]
`logging.info('Usage: ./chronogg.py <Authorization Token>')`

When paste Authorization Token and run chronogg.py
![2018-12-03_185441](https://user-images.githubusercontent.com/41187653/49395502-92e77a00-f72e-11e8-96fd-de82ecaa8fec.png)

**Comment by stickerx** [comment]
('Usage: ./chronogg.py <Authorization Token>')

**Comment by joaopsys** [comment]
Hi, how exactly are you executing the script? Should probably be ```python chronogg.py "Token"``` in your case. Try with and without quotes.

**Comment by stickerx** [comment]
same probleme  
<line 144>

` logging.info('Usage: ./chronogg.py <Authorization Token>')`

**Comment by joaopsys** [comment]
I need to read the error message, you can omit most of it if it contains your token, but I need to be able to read at least the start of the error message

**Comment by joaopsys** [comment]
That is just a line that prints information on how you should pass your token to the script. If you are reading that line, that means the script is not recognizing your authorization token, or it's an empty string.

**Comment by stickerx** [comment]
Should put email and user To work ?
in
.config.example

**Comment by joaopsys** [comment]
No, .config is not needed for this to work, that is optional. You are not adding the < before and > after the token right? The < and > should not be used.

For example I execute my script like this:
```./chronogg.py "JWT aBJ0eXAiOabcdefght"```

**Comment by stickerx** [comment]
put in green color, same message
![2018-12-04_165429](https://user-images.githubusercontent.com/41187653/49458932-c6d1a680-f7e5-11e8-9b70-c2896083875a.png)

**Comment by joaopsys** [comment]
I don't understand what you are doing. Why are you editing the source code?

**Comment by stickerx** [comment]
I did not editing anything ?

**Comment by joaopsys** [comment]
By the looks of it, this is the first time you are running a Python script, which is fine so please follow these instructions.

In the folder where the script is located, SHIFT + Right click anywhere and there should be an option saying 'Open terminal here'. A terminal will hopefully open.

In that terminal, type ```python chronogg.py "JWT abcdef"``` with your Token in there. The script should run without errors.

**Comment by stickerx** [comment]
when follow these instructions.
now look 
![2018-12-04_173854](https://user-images.githubusercontent.com/41187653/49461657-174c0280-f7ec-11e8-8768-39305b30c33e.png)

**Comment by joaopsys** [comment]
Ok that is some progress. But I can see through the blur and your token is not starting with JWT. You need to paste the entire token (including the JWT part) inside the quotes.

**Comment by stickerx** [comment]
Yes thanks,  Its work now with including the JWT 

Should must every day bring new token or permanent use this

**Comment by joaopsys** [comment]
Now that it worked, it should just be a matter of double clicking the script. The script will remember your token when it's valid. You can try running only with ```python chronogg.py``` now, without any token. It will say 'Coin already clicked' if everything is done right.

**Comment by stickerx** [comment]
magical x)
put only `python chronogg.py`
 say 'Coin already clicked' 

But where was saved token ?

**Comment by joaopsys** [comment]
It is inside inside a hidden file. You need to have Windows configured to show hidden files and you will see the file .chronogg in that same folder.

**Comment by stickerx** [comment]
now i see him,
 thank you very much again for you  help
![2018-12-04_181449](https://user-images.githubusercontent.com/41187653/49463534-95aaa380-f7f0-11e8-9cd4-b5c9e003d274.png)

**Comment by joaopsys** [comment]
No problem. Glad it worked.
