### ISSUE TITLE
Error 401: Unauthorized

### ISSUE THREAD

**Issue by ricmetal** [joaopsys/AutoChronoGG#3]
hello,
i've set the token, and cookie, but keep getting:

"Fetching https://api.chrono.gg/quest/spin
Error processing webpage: HTTP Error 401: Unauthorized
An error occurred while fetching results (probably expired/invalid cookie). Terminating...
Press any key to continue . . ."

i'm logged in though (meaning there is a set cookie, correct?)
is this script still working correctly? i think i've set up everything like i should

**Comment by ricmetal** [comment]
hello again,
ok, i don't know what to tell you but i'm not getting the error anymore. :/
obrigado

**Comment by joaopsys** [comment]
Good to know! :)
